version: '3.3'

services:

    elastic01:
        image: "docker.elastic.co/elasticsearch/elasticsearch:8.4.1"
        hostname: elastic01
        networks:
            - elasticnet
        environment:
            - node.name=node1
            - cluster.name=bskp-cluster
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
            - discovery.seed_hosts=elastic01,elastic02
            - cluster.initial_master_nodes=node1
            - xpack.security.enabled=false
            - bootstrap.memory_lock=false
        volumes:
            - ./elastic01:/usr/share/elasticsearch/data

    elastic02:
        image: "docker.elastic.co/elasticsearch/elasticsearch:8.4.1"
        hostname: elastic02
        networks:
            - elasticnet
        environment:
            - node.name=node2
            - cluster.name=bskp-cluster
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
            - discovery.seed_hosts=elastic02,elastic01
            - cluster.initial_master_nodes=node1
            - xpack.security.enabled=false
            - bootstrap.memory_lock=false
        volumes:
            - ./elastic02:/usr/share/elasticsearch/data

networks:
  elasticnet:
    external: true
