version: "3.3"
services:
  cassandra:
    image: "cassandra:3.11.5"
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - cassandra:/var/lib/cassandra
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.1"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic:/usr/share/elasticsearch/data
  ui:
    build:
      context: ../ui
      args:
        VERSION: "v3.1.8"
    ports:
      - "4201:4201"
  dashboard:
    build:
      context: ../dashboard
      args:
        VERSION: "v1.0.3"
    ports:
      - "10000:10000"
volumes:
  cassandra:
    driver: local
  elastic:
    driver: local
