version: "3.9"
services:
  cassandra:
    image: "cassandra:3.11.5"
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.1"
    environment:
      - discovery.type=single-node
  platform:
    build:
        dockerfile: Dockerfile
        context: ./platform
    image: boodskapiot/platform
    ports:
      - "18080:18080"
      - "19090:19090"
    depends_on:
      - cassandra
      - elastic
  ui:
    build:
        dockerfile: Dockerfile
        context: ./ui
    image: boodskapiot/ui
    ports:
      - "4201:4201"
    depends_on:
      - platform
  dashboard:
    build:
        dockerfile: Dockerfile
        context: ./dashboard
    image: boodskapiot/dashboard
    ports:
      - "10000:10000"
    depends_on:
      - ui
  gateway:
    build:
        dockerfile: Dockerfile
        context: ./gateway
    image: boodskapiot/gateway
    ports:
      - "80:80"
    depends_on:
      - dashboard
