version: "3.9"
services:
  cassandra:
    image: "mcfongtw/rpi-cassandra:3.11"
  elastic:
    build:
        dockerfile: Dockerfile
        context: ./elastic-rpi
    image: boodskapiot/elastic-rpi
  platform:
    build:
        dockerfile: Dockerfile
        context: ./platform-rpi
    image: boodskapiot/platform-rpi
    depends_on:
      - cassandra
      - elastic
  ui:
    build:
        dockerfile: Dockerfile
        context: ./ui-rpi
    image: boodskapiot/ui-rpi
    depends_on:
      - platform
  dashboard:
    build:
        dockerfile: Dockerfile
        context: ./dashboard-rpi
    image: boodskapiot/dashboard-rpi
    depends_on:
      - platform
  gateway:
    build:
        dockerfile: Dockerfile
        context: ./gateway-rpi
    image: boodskapiot/gateway-rpi
    ports:
      - "80:80"
    depends_on:
      - ui
      - dashboard
