version: "3.9"
services:
  cassandra:
    image: "cassandra:3.11.5"
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - cassandra:/var/lib/cassandra
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.1"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    environment:
      SERVER_NAME: kibana.boodskap.xyz
      ELASTICSEARCH_HOSTS: http://elastic
  ui:
    image: boodskapiot/ui
    ports:
      - "4201:4201"
    volumes:
      - ${HOME}/git2/boodskap-iot-platform/boodskap-iot-platform/boodskap-apigen/src/main/resources/api/api.yaml
  dashboard:
    image: boodskapiot/dashboard
    ports:
      - "10000:10000"
    depends_on:
      - ui
  gateway:
    image: boodskapiot/gatewaydev
    ports:
      - "80:80"
    depends_on:
      - dashboard
volumes:
  cassandra:
    driver: local
  elastic:
    driver: local
  platformdata:
    driver: local
  platformwork:
    driver: local
