version: "3.3"
services:
  cassandra:
    image: "cassandra:3.11.5"
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - cassandra:/var/lib/cassandra
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.1"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic:/usr/share/elasticsearch/data
  platform:
    image: boodskapiot/platform:4.0.0-0008
    ports:
      - "18080:18080"
      - "19090:19090"
      - "1883:1883"
      - "8083:8083"
    depends_on:
      - cassandra
      - elastic
    volumes:
      - platformdata:/home/boodskap/data
      - platformwork:/home/boodskap/work
  ui:
    image: boodskapiot/ui:3.0.20
    ports:
      - "4201:4201"
    depends_on:
      - platform
  dashboard:
    image: boodskapiot/dashboard:1.0.3
    ports:
      - "10000:10000"
    depends_on:
      - ui
  gateway:
    image: boodskapiot/gateway
    ports:
      - "80:80"
    depends_on:
      - dashboard
volumes:
  cassandra:
    driver: local
  elastic:
    driver: local
  platformdata:
    driver: local
  platformwork:
    driver: local
