networks:
  bskpnet:
    external: true
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.5.0'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - '2181:2181'
    networks:
      bskpnet:
        ipv4_address: 172.38.0.10
    volumes:
      - './data/zoo/data:/var/lib/zookeeper/data'
      - './data/zoo/log:/var/lib/zookeeper/log'
  redis:
    image: redis
    command:
      - redis-server
      - /etc/redis/redis.conf
    volumes:
      - './data/redis:/data'
      - './config/redis/redis.conf:/etc/redis/redis.conf'
    ports:
      - '6371:6379'
      - '16371:16379'
    networks:
      bskpnet:
        ipv4_address: 172.38.0.25
  kafka:
    image: 'confluentinc/cp-kafka:7.5.0'
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:19092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    networks:
      bskpnet:
        ipv4_address: 172.38.0.11
    volumes:
      - './data/kafka:/var/lib/kafka/data'
    depends_on:
      - zookeeper
  elastic:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:9.0.1'
    hostname: elastic
    ports:
      - '9200:9200'
    networks:
      bskpnet:
        ipv4_address: 172.38.0.12
    environment:
      - node.name=node1
      - cluster.name=bskp-cluster
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          curl -s http://elastic:9200/_cluster/health | grep -q
          '"status":"green"'
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - './data/elastic:/usr/share/elasticsearch/data'
  boodskap:
    image: 'boodskapiot/platform-v8:8.0.0'
    container_name: boodskap
    ports:
      - '18080:18080'
    networks:
      bskpnet:
    environment:
      IS_SHARED_FOLDER: true
      ALLOW_TEST_MODE: true
      DATA_FOLDER_PATH: /shared
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      REDIS_HOST: redis
      ELASTIC_SEARCH_HOST: elastic
    volumes:
      - './data/boodskap/shared:/shared'
      - './data/boodskap/config:/etc/boodskap'
    depends_on:
      - zookeeper
      - redis
      - kafka
      - elastic

  swagger:
    image: swaggerapi/swagger-editor
    hostname: swagger
    networks:
      bskpnet:

  nginx:
    image: 'nginx:stable-perl'
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      bskpnet:
    volumes:
      - './config/nginx/conf.d:/etc/nginx/conf.d'
      - './data/nginx/static/apps:/static/apps'
    depends_on:
      - zookeeper
      - redis
      - kafka
      - elastic
      - boodskap
      - swagger
