version: '3.3'

services:

    emqx01:
        image: boodskapiot/emqx:3.2.8
        hostname: emqx01.io
        ports:
            - "8083:8083"
            - "1883:1883"
        networks:
            - emqxnet
            - platformnet
        environment:
            EMQX_HOST: "emqx01.io"
            EMQX_NAME: "emqx01"
        volumes:
            - ./emqx01:/efs/emqx

networks:
  emqxnet:
    external: true
  platformnet:
    external: true
